[font]
size = 9

[cursor.style]
blinking = "on"

[keyboard]
bindings = [{ key = "Return",   mods = "Super|Control", action = "SpawnNewInstance" }, { key = "Return",   mods = "Super|Alt", action = "CreateNewWindow" }]